name: Build & Upload

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: zip goblins.mrpack pack/modrinth.index.json

      - name: Upload
        uses: actions/upload-artifact@v7.0.1
        with:
          path: goblins.mrpack
          name: goblins.mrpack
          archive: false
          if-no-files-found: error
          retention-days: 90
